/**
 * Firewall inspection and the small number of changes the dashboard may make.
 *
 * There is no "run this nft command" operation, and there never will be. The
 * dashboard can ask for one of a handful of named outcomes — open HTTPS, close
 * HTTPS, restrict SSH to a source, apply the baseline — and the agent
 * generates the ruleset itself from a template it owns. A firewall that a web
 * request can write arbitrary rules into is a firewall an attacker can write
 * arbitrary rules into.
 *
 * KAIROS keeps its rules in a dedicated `inet kairos` table so that applying
 * them never clobbers rules some other part of the system installed. Docker in
 * particular writes its own chains and is extremely unhappy when they vanish.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { register } from '../registry.js';
import { run, tryRun, binaryAvailable } from '../exec.js';
import { config } from '../config.js';
import { PATTERNS } from '../validate.js';
import { listeningSockets, assessExposure } from './network.js';

const RULES_FILE = join(config.configRoot, 'nftables.conf');
const STATE_FILE = join(config.configRoot, 'firewall-state.json');

/**
 * What the operator has asked the firewall to do. Kept as data, so the
 * ruleset is regenerated from intent rather than edited in place — editing
 * rules in place is how a "close HTTPS" leaves the accept rule behind under a
 * slightly different match.
 */
export interface FirewallState {
  httpsOpen: boolean;
  httpOpen: boolean;
  /** null means SSH is closed entirely; a CIDR restricts it to that source. */
  sshFrom: string | null;
  updatedAt: string;
}

const DEFAULT_STATE: FirewallState = {
  httpsOpen: true,
  httpOpen: true,
  sshFrom: null,
  updatedAt: new Date(0).toISOString(),
};

async function readState(): Promise<FirewallState> {
  try {
    const raw = await readFile(STATE_FILE, 'utf8');
    const parsed = JSON.parse(raw) as Partial<FirewallState>;
    return {
      httpsOpen: parsed.httpsOpen ?? DEFAULT_STATE.httpsOpen,
      httpOpen: parsed.httpOpen ?? DEFAULT_STATE.httpOpen,
      sshFrom: parsed.sshFrom ?? null,
      updatedAt: parsed.updatedAt ?? DEFAULT_STATE.updatedAt,
    };
  } catch {
    return { ...DEFAULT_STATE };
  }
}

async function writeState(state: FirewallState): Promise<void> {
  await mkdir(config.configRoot, { recursive: true, mode: 0o750 });
  await writeFile(STATE_FILE, JSON.stringify(state, null, 2), { mode: 0o640 });
}

/**
 * Generate the KAIROS ruleset.
 *
 * Nothing in here is interpolated from a request except `sshFrom`, which is
 * validated against a CIDR pattern before it reaches this function and
 * re-validated here — the function is the last thing between a string and a
 * file that the kernel will parse as policy.
 */
function renderRuleset(state: FirewallState): string {
  if (state.sshFrom !== null && !PATTERNS.cidr.test(state.sshFrom)) {
    throw new Error('Refusing to write a firewall rule with a malformed source address');
  }

  const lines = [
    '#!/usr/sbin/nft -f',
    '#',
    '# Generated by the KAIROS server agent. Edits here are overwritten.',
    '# Intent lives in /etc/kairos/firewall-state.json.',
    '#',
    '# Only the `kairos` table is flushed, so Docker\'s chains survive.',
    '',
    'table inet kairos',
    'delete table inet kairos',
    '',
    'table inet kairos {',
    '    chain input {',
    '        type filter hook input priority filter; policy drop;',
    '',
    '        # Loopback is how the API reaches PostgreSQL and Redis.',
    '        iif lo accept',
    '',
    '        # Replies to connections this machine made.',
    '        ct state established,related accept',
    '        ct state invalid drop',
    '',
    '        # ICMP, so the network keeps working. Path MTU discovery breaks',
    '        # silently and horribly without it.',
    '        ip protocol icmp icmp type { echo-request, destination-unreachable, time-exceeded, parameter-problem } accept',
    '        ip6 nexthdr icmpv6 accept',
    '',
  ];

  if (state.httpsOpen) {
    lines.push('        # HTTPS — the only port the platform needs from outside.', '        tcp dport 443 accept', '');
  }
  if (state.httpOpen) {
    lines.push('        # HTTP, for the redirect to HTTPS and ACME challenges.', '        tcp dport 80 accept', '');
  }
  if (state.sshFrom) {
    lines.push(
      `        # SSH, restricted to ${state.sshFrom}.`,
      `        ip saddr ${state.sshFrom} tcp dport 22 accept`,
      '',
    );
  } else {
    lines.push('        # SSH is not open from the network. Use the console.', '');
  }

  lines.push(
    '        # Everything else is dropped by the policy above. PostgreSQL,',
    '        # Redis and the storage ports are never listed here, which is why',
    '        # they are never reachable.',
    '    }',
    '',
    '    chain forward {',
    '        type filter hook forward priority filter; policy drop;',
    '        # Docker installs its own forward rules in its own table.',
    '        ct state established,related accept',
    '    }',
    '',
    '    chain output {',
    '        type filter hook output priority filter; policy accept;',
    '    }',
    '}',
    '',
  );

  return lines.join('\n');
}

/* --------------------------------------------------------------- status */

export type FirewallBackend = 'nftables' | 'ufw' | 'none';

export async function firewallStatus() {
  const hasNft = binaryAvailable('nft');
  const hasUfw = binaryAvailable('ufw');

  let backend: FirewallBackend = 'none';
  let active = false;
  let defaultPolicy: string | null = null;
  let kairosTable = false;
  let raw: string | null = null;

  if (hasNft) {
    raw = await tryRun('nft', ['list', 'ruleset'], { timeoutMs: 15_000 });
    if (raw !== null) {
      backend = 'nftables';
      kairosTable = /table inet kairos/.test(raw);
      const policy = /chain input \{[\s\S]*?policy (\w+)/.exec(raw)?.[1] ?? null;
      defaultPolicy = policy;
      // "Active" means inbound is denied by default. A loaded ruleset whose
      // input policy is accept is a firewall in name only.
      active = policy === 'drop';
    }
  }

  if (!active && hasUfw) {
    const ufwStatus = await tryRun('ufw', ['status', 'verbose'], { timeoutMs: 15_000 });
    if (ufwStatus && /Status:\s*active/i.test(ufwStatus)) {
      backend = 'ufw';
      active = true;
      defaultPolicy = /Default:\s*(\w+)\s*\(incoming\)/i.exec(ufwStatus)?.[1] ?? null;
      raw = ufwStatus;
    }
  }

  const state = await readState();
  const sockets = await listeningSockets();
  const exposure = assessExposure(sockets);

  return {
    backend,
    active,
    defaultPolicy,
    kairosTable,
    intent: state,
    exposure: exposure.filter((finding) => finding.severity !== 'ok'),
    blockedByDesign: [
      { port: 5432, service: 'PostgreSQL' },
      { port: 6379, service: 'Redis' },
      { port: 9000, service: 'Object storage' },
      { port: 9001, service: 'Storage console' },
    ],
    open: [
      ...(state.httpsOpen ? [{ port: 443, service: 'HTTPS' }] : []),
      ...(state.httpOpen ? [{ port: 80, service: 'HTTP' }] : []),
      ...(state.sshFrom ? [{ port: 22, service: `SSH from ${state.sshFrom}` }] : []),
    ],
  };
}

/** Write the ruleset and load it, then confirm it actually took. */
async function applyRuleset(state: FirewallState, emit: (text: string) => void): Promise<void> {
  if (!binaryAvailable('nft')) {
    throw new Error('nftables is not installed. Install it with: apt-get install nftables');
  }

  const ruleset = renderRuleset(state);
  await mkdir(config.configRoot, { recursive: true, mode: 0o750 });
  await writeFile(RULES_FILE, ruleset, { mode: 0o640 });
  emit(`Wrote ${RULES_FILE}\n`);

  // `nft -c -f` checks without loading. Loading a ruleset that does not parse
  // leaves the previous one in place, but loading one that parses and is wrong
  // locks you out, so check first and verify after.
  const check = await run('nft', ['-c', '-f', RULES_FILE], { timeoutMs: 15_000, allowNonZeroExit: true });
  if (check.code !== 0) {
    throw new Error(`Generated ruleset does not parse, so nothing was applied: ${check.stderr.trim()}`);
  }

  emit('Ruleset parses. Applying...\n');
  const applied = await run('nft', ['-f', RULES_FILE], { timeoutMs: 20_000, allowNonZeroExit: true });
  if (applied.code !== 0) {
    throw new Error(`Failed to apply the ruleset: ${applied.stderr.trim()}`);
  }

  await writeState({ ...state, updatedAt: new Date().toISOString() });

  const after = await firewallStatus();
  if (!after.active) {
    throw new Error('The ruleset loaded but the input policy is not drop. Check for another tool managing nftables.');
  }
  emit('Applied. Inbound default is drop.\n');
}

/* ---------------------------------------------------------- operations */

register(
  {
    id: 'firewall_status',
    summary: 'Firewall backend, default policy and which ports are open',
    category: 'firewall',
    danger: false,
    timeoutMs: 30_000,
    async run() {
      const status = await firewallStatus();
      const lines = [
        `Firewall     ${status.active ? 'ACTIVE' : 'NOT ACTIVE'}`,
        `Backend      ${status.backend}`,
        `Inbound      ${status.defaultPolicy ?? 'unknown'}`,
        '',
        'Open:',
        ...(status.open.length ? status.open.map((entry) => `  ${entry.port}  ${entry.service}`) : ['  nothing']),
        '',
        'Blocked by design:',
        ...status.blockedByDesign.map((entry) => `  ${entry.port}  ${entry.service}`),
      ];
      if (!status.active) {
        lines.push('', 'The firewall is not denying inbound traffic by default. Run the setup wizard or apply the baseline.');
      }
      if (status.exposure.length > 0) {
        lines.push('', 'Findings:', ...status.exposure.map((finding) => `  ! ${finding.message}`));
      }
      return { data: status, text: lines.join('\n') };
    },
  },
  {
    id: 'firewall_rules',
    summary: 'The loaded ruleset, verbatim',
    category: 'firewall',
    danger: false,
    timeoutMs: 20_000,
    async run() {
      if (binaryAvailable('nft')) {
        const raw = await tryRun('nft', ['list', 'ruleset'], { timeoutMs: 15_000 });
        if (raw !== null) return { data: { backend: 'nftables', ruleset: raw }, text: raw || '(empty ruleset)' };
      }
      if (binaryAvailable('ufw')) {
        const raw = await tryRun('ufw', ['status', 'numbered'], { timeoutMs: 15_000 });
        if (raw !== null) return { data: { backend: 'ufw', ruleset: raw }, text: raw };
      }
      return { data: { backend: 'none', ruleset: null }, text: 'No firewall tool is installed on this host.' };
    },
  },
  {
    id: 'firewall_apply_baseline',
    summary: 'Install the KAIROS ruleset: deny inbound, allow HTTPS, keep the database private',
    category: 'firewall',
    danger: true,
    confirmPhrase: 'APPLY FIREWALL',
    timeoutMs: 60_000,
    async run({ emit }) {
      const state = await readState();
      await applyRuleset(state, emit);
      const status = await firewallStatus();
      return { data: status, text: 'Baseline firewall applied.' };
    },
  },
  {
    id: 'firewall_open_https',
    summary: 'Allow inbound HTTPS on 443',
    category: 'firewall',
    danger: true,
    confirmPhrase: 'OPEN HTTPS',
    timeoutMs: 60_000,
    async run({ emit }) {
      const state = await readState();
      await applyRuleset({ ...state, httpsOpen: true }, emit);
      return { data: await firewallStatus(), text: 'HTTPS is open on 443.' };
    },
  },
  {
    id: 'firewall_close_https',
    summary: 'Stop accepting inbound HTTPS',
    category: 'firewall',
    danger: true,
    confirmPhrase: 'CLOSE HTTPS',
    timeoutMs: 60_000,
    async run({ emit }) {
      const state = await readState();
      emit('Closing 443. Anything connecting from outside will stop working, including this dashboard if you reached it that way.\n');
      await applyRuleset({ ...state, httpsOpen: false }, emit);
      return { data: await firewallStatus(), text: 'HTTPS is closed.' };
    },
  },
  {
    id: 'firewall_configure_ssh',
    summary: 'Restrict SSH to one source network, or close it entirely',
    category: 'firewall',
    danger: true,
    confirmPhrase: 'CHANGE SSH ACCESS',
    timeoutMs: 60_000,
    args: {
      source: {
        type: 'string',
        pattern: PATTERNS.cidr,
        maxLength: 18,
        required: false,
        describe: 'CIDR allowed to reach SSH, e.g. 192.168.1.0/24. Omit to close SSH.',
      },
    },
    async run({ args, emit }) {
      const source = args['source'] === undefined ? null : String(args['source']);
      const state = await readState();

      if (source === null) {
        emit('Closing SSH. Make sure you have physical access to this machine before continuing.\n');
      } else {
        emit(`Restricting SSH to ${source}.\n`);
      }

      await applyRuleset({ ...state, sshFrom: source }, emit);
      return {
        data: await firewallStatus(),
        text: source ? `SSH is reachable from ${source} only.` : 'SSH is closed at the firewall.',
      };
    },
  },
);

export { renderRuleset, readState as readFirewallState, RULES_FILE };
