#!/usr/bin/env bash
###############################################################################
# KAIROS DB — one-shot server bootstrap (Ubuntu / Debian)
#
#   sudo ./scripts/bootstrap.sh
#
# Takes a fresh laptop install to a running Kairos node: packages, Docker,
# firewall, fail2ban, directories, secrets, and the stack itself.
# Idempotent — safe to re-run.
###############################################################################
set -euo pipefail

if [[ $EUID -ne 0 ]]; then echo "Run as root." >&2; exit 1; fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATA_ROOT="${KAIROS_DATA_ROOT:-/var/lib/kairos}"

echo "==> [1/7] Packages"
apt-get update -qq
apt-get install -y -qq \
  ca-certificates curl gnupg ufw fail2ban nftables \
  postgresql-client rclone jq

echo "==> [2/7] Docker"
if ! command -v docker >/dev/null 2>&1; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi
systemctl enable --now docker

echo "==> [3/7] Directories"
mkdir -p "$DATA_ROOT"/{storage,backups,logs}
mkdir -p /var/log/kairos
chmod 750 "$DATA_ROOT"
touch /var/log/kairos/security.log
chmod 640 /var/log/kairos/security.log

echo "==> [4/7] Secrets"
if [[ ! -f "$ROOT/.env" ]]; then
  cp "$ROOT/.env.example" "$ROOT/.env"
  {
    echo ""
    echo "# --- generated by bootstrap.sh on $(date -Is) ---"
    echo "JWT_SECRET=$(openssl rand -hex 32)"
    echo "JWT_REFRESH_SECRET=$(openssl rand -hex 32)"
    echo "ENCRYPTION_KEY=$(openssl rand -hex 32)"
    echo "POSTGRES_PASSWORD=$(openssl rand -hex 24)"
    echo "POSTGRES_APP_PASSWORD=$(openssl rand -hex 24)"
    echo "REDIS_PASSWORD=$(openssl rand -hex 24)"
    echo "S3_ACCESS_KEY=kairos-$(openssl rand -hex 6)"
    echo "S3_SECRET_KEY=$(openssl rand -hex 24)"
  } >> "$ROOT/.env"
  chmod 600 "$ROOT/.env"
  echo "    generated $ROOT/.env — back it up somewhere safe."
  echo "    Losing ENCRYPTION_KEY means every stored project credential is unrecoverable."
else
  echo "    .env already exists, leaving it alone"
fi

echo "==> [5/7] Firewall"
SSH_ALLOW_FROM="${SSH_ALLOW_FROM:-}" "$ROOT/infrastructure/firewall/ufw-setup.sh"
"$ROOT/infrastructure/firewall/docker-user.sh"

echo "==> [6/7] Fail2ban"
cp "$ROOT/infrastructure/fail2ban/jail.local" /etc/fail2ban/jail.local
cp "$ROOT/infrastructure/fail2ban/filter.d/"kairos-*.conf /etc/fail2ban/filter.d/
systemctl enable --now fail2ban
systemctl restart fail2ban
sleep 2
fail2ban-client status || true

echo "==> [7/7] Stack"
cd "$ROOT"
docker compose -f docker-compose.prod.yml up -d --build

cat <<'EOF'

Bootstrap complete.

Next:
  1. Point DNS at this machine, or start a Cloudflare Tunnel:
       docker compose -f docker-compose.prod.yml --profile tunnel up -d
  2. Edit infrastructure/nginx/sites/kairos.conf and replace example.com
  3. Issue certificates:
       ./scripts/tls-issue.sh your-domain.com
  4. Verify the perimeter:
       ./scripts/verify-security.sh
EOF
