#!/usr/bin/env bash
###############################################################################
# KAIROS DB — refresh Cloudflare edge ranges
#
#   ./scripts/update-cloudflare-ips.sh && docker compose exec nginx nginx -s reload
#
# Cloudflare changes these occasionally. A stale list means real_ip stops
# working for some clients, so their true IP is replaced by Cloudflare's — and
# fail2ban then bans a Cloudflare edge node, taking a slice of your users down
# with the attacker. Run this monthly from cron.
###############################################################################
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/infrastructure/nginx/snippets/cloudflare-realip.conf"
LIST="$ROOT/infrastructure/firewall/cloudflare-ips.txt"

V4=$(curl -fsS https://www.cloudflare.com/ips-v4)
V6=$(curl -fsS https://www.cloudflare.com/ips-v6)

[[ -n "$V4" && -n "$V6" ]] || { echo "Empty response from Cloudflare; keeping existing list." >&2; exit 1; }

{
  echo "### Generated by scripts/update-cloudflare-ips.sh on $(date -Is)"
  echo "### Do not edit by hand."
  echo
  while read -r cidr; do [[ -n "$cidr" ]] && echo "set_real_ip_from $cidr;"; done <<< "$V4"
  while read -r cidr; do [[ -n "$cidr" ]] && echo "set_real_ip_from $cidr;"; done <<< "$V6"
  echo
  echo "# Docker bridge — cloudflared sidecar."
  echo "set_real_ip_from 172.16.0.0/12;"
  echo
  echo "real_ip_header    CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$OUT"

{
  echo "# Generated $(date -Is)"
  echo "$V4"
} > "$LIST"

echo "Updated $OUT"
echo "Reload nginx:  docker compose -f docker-compose.prod.yml exec nginx nginx -s reload"
