/**
 * Agent configuration.
 *
 * Everything here is read from the environment or from files under /etc/kairos
 * that root owns. Nothing is configurable over the wire: an agent whose
 * allowlist or data root could be changed by a request is an agent with no
 * allowlist at all.
 */
import { readFileSync, existsSync } from 'node:fs';
import { randomBytes } from 'node:crypto';

function fromFileOrEnv(envKey: string, filePath: string): string | null {
  const direct = process.env[envKey];
  if (direct && direct.trim()) return direct.trim();
  if (existsSync(filePath)) {
    const contents = readFileSync(filePath, 'utf8').trim();
    if (contents) return contents;
  }
  return null;
}

/** Where the agent listens. A path, not a port — see SOCKET_PATH below. */
const SOCKET_PATH = process.env['KAIROS_AGENT_SOCKET'] ?? '/run/kairos/server-agent.sock';

/**
 * The shared secret the API signs its requests with.
 *
 * Generated by install-server.sh into /etc/kairos/agent.token (0640,
 * root:kairos). In development the agent will mint an ephemeral one and say so
 * loudly, because a dev agent that refuses to start is a dev agent nobody runs.
 */
let token = fromFileOrEnv('KAIROS_AGENT_TOKEN', '/etc/kairos/agent.token');
let tokenIsEphemeral = false;
if (!token) {
  token = randomBytes(32).toString('hex');
  tokenIsEphemeral = true;
}

export const config = {
  socketPath: SOCKET_PATH,

  /**
   * Optional loopback fallback for the case where the API runs in a container
   * that cannot see the host's socket namespace. Off unless explicitly set,
   * and 127.0.0.1 only — binding this to 0.0.0.0 would put a root-capable
   * control plane on the network, which is the single worst thing this design
   * can do.
   */
  tcpPort: process.env['KAIROS_AGENT_TCP_PORT'] ? Number(process.env['KAIROS_AGENT_TCP_PORT']) : null,
  tcpHost: '127.0.0.1',

  token,
  tokenIsEphemeral,

  /** Unix group allowed to talk to the socket. */
  socketGroup: process.env['KAIROS_AGENT_GROUP'] ?? 'kairos',

  dataRoot: process.env['KAIROS_DATA_ROOT'] ?? '/var/lib/kairos',
  configRoot: process.env['KAIROS_CONFIG_ROOT'] ?? '/etc/kairos',
  projectRoot: process.env['KAIROS_PROJECT_ROOT'] ?? '/opt/kairos',

  /** Requests older than this are refused, so a captured request cannot be replayed tomorrow. */
  maxClockSkewMs: 30_000,

  /** A PTY with nobody typing at it is an open door. */
  ptyIdleTimeoutMs: Number(process.env['KAIROS_PTY_IDLE_MS'] ?? 15 * 60_000),
  ptyMaxLifetimeMs: Number(process.env['KAIROS_PTY_MAX_MS'] ?? 60 * 60_000),

  /** Hard ceiling on captured output, so a runaway command cannot exhaust memory. */
  maxOutputBytes: 8 * 1024 * 1024,

  version: '0.1.0',
} as const;

export type AgentConfig = typeof config;
